KAFKA_BROKERS: localhost:9092
KAFKA_CLIENT_ID: client1
KAFKA_MESSAGE_COUNT: 1000
KAFKA_GROUP_ID_CONFIG: consumerGroup1
GREET_TOPIC_NAME: demo
KAFKA_MAX_NO_MESSAGE_FOUND_COUNT: 100
KAFKA_OFFSET_RESET_LATEST: latest
OFFSET_RESET_EARLIER: earliest
RETRY_BACKOFF_MS_CONFIG: 1000
REQUEST_TIMEOUT_MS_CONFIG: 15000
RETRIES_CONFIG: 3
MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 1

